# Generated by Django 4.2.7 on 2023-12-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='type',
            field=models.CharField(default='other', max_length=16),
            preserve_default=False,
        ),
    ]
