# Generated by Django 4.2.7 on 2023-12-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlist_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='winner',
        ),
    ]
