# Generated by Django 4.2.7 on 2023-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlist_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
