# Generated by Django 4.2.7 on 2023-12-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
